'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'he' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, namespace?: string) => string
  isHebrew: boolean
  getLanguageClasses: (baseClasses?: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation data
const translations = {
  he: {
    // Navigation
    'navigation.dashboard': 'לוח בקרה',
    'navigation.myAgents': 'הסוכנים שלי',
    'navigation.pipelineBuilder': 'בנייה Drag-Drop',
    'navigation.agentMarketplace': 'חנות סוכנים',
    'navigation.providerMarketplace': 'ספקים',
    'navigation.analytics': 'ניתוחים',
    'navigation.templates': 'תבניות',
    'navigation.whiteLabel': 'מותג לבן',
    'navigation.settings': 'הגדרות',
    'navigation.createAgent': 'צור סוכן',

    // Agent Creation
    'agents.buildAgentDesc': 'צור סוכן בעזרת בנייה מתקדמת',
    'agents.createNewAgent': 'צור סוכן חדש',
    'agents.agentName': 'שם הסוכן',
    'agents.description': 'תיאור',
    'agents.systemPrompt': 'הנחיות למערכת',
    'agents.enterAgentName': 'הכנס שם סוכן',
    'agents.enterDescription': 'הכנס תיאור',
    'agents.enterSystemPrompt': 'הכנס הנחיות למערכת',
    'agents.systemPromptDesc': 'הנחיות אלו יקבעו את התנהגות הסוכן',
    'agents.basicInformation': 'מידע בסיסי',
    'agents.basicInfoDesc': 'הגדר את הפרטים הבסיסיים של הסוכן',
    'agents.selectProviders': 'בחר ספקים',
    'agents.buildPipeline': 'בנה צינור',
    'agents.agentSummary': 'סיכום הסוכן',
    'agents.testAgent': 'בדוק סוכן',
    'agents.speechToText': 'דיבור לטקסט',
    'agents.languageModel': 'מודל שפה',
    'agents.textToSpeech': 'טקסט לדיבור',
    'agents.selectSTTProvider': 'בחר ספק דיבור לטקסט',
    'agents.selectLLMProvider': 'בחר ספק מודל שפה',
    'agents.selectTTSProvider': 'בחר ספק טקסט לדיבור',
    'agents.selectRealtimeProvider': 'בחר ספק זמן אמת',
    'agents.realtimeSpeech': 'דיבור זמן אמת',
    'agents.individualProviders': 'ספקים עצמאיים',
    'agents.configuration': 'הגדרות',
    'agents.testYourAgent': 'בדוק את הסוכן שלך',
    'agents.testAgentDesc': 'בדוק את הסוכן לפני פרסום',
    'agents.notSelected': 'לא נבחר',
    'agents.transport': 'תחבורה',
    'agents.backToAgents': 'חזור לסוכנים',
    'agents.startTest': 'התחל בדיקה',
    'agents.startingTest': 'מתחיל בדיקה...',
    'agents.progress': 'התקדמות',
    'agents.next': 'הבא',
    'agents.previous': 'הקודם',
    'agents.saveAgent': 'שמור סוכן',
    'agents.saving': 'שומר...',
    'agents.testing': 'בודק...',
    'agents.nameRequired': 'שם הסוכן נדרש',
    'agents.sttProviderRequired': 'ספק דיבור לטקסט נדרש',
    'agents.llmProviderRequired': 'ספק מודל שפה נדרש',
    'agents.ttsProviderRequired': 'ספק טקסט לדיבור נדרש',
    'agents.sttApiKeyRequired': 'מפתח API לדיבור לטקסט נדרש',
    'agents.llmApiKeyRequired': 'מפתח API למודל שפה נדרש',
    'agents.ttsApiKeyRequired': 'מפתח API לטקסט לדיבור נדרש',

    // Providers
    'providers.providerMarketplace': 'ספקי AI',
    'providers.chooseFromProviders': 'בחר מתוך',
    'providers.aiProviders': 'ספקי AI',
    'providers.selectProvider': 'בחר ספק',
    'providers.selectProviderDesc': 'בחר ספק AI מתאים',
    'providers.selectSTTProvider': 'בחר ספק דיבור לטקסט',
    'providers.selectLLMProvider': 'בחר ספק מודל שפה',
    'providers.selectTTSProvider': 'בחר ספק טקסט לדיבור',
    'providers.sttProviderDesc': 'ספק המרת דיבור לטקסט',
    'providers.llmProviderDesc': 'ספק מודל שפה מתקדם',
    'providers.ttsProviderDesc': 'ספק המרת טקסט לדיבור',
    'providers.realtimeProviderDesc': 'ספק דיבור-לדיבור בזמן אמת',
    'providers.selectRealtimeProvider': 'בחר ספק דיבור זמן אמת',
    'providers.quickSelect': 'בחירה מהירה',
    'providers.chooseProvider': 'בחר ספק',
    'providers.browseProviders': 'עיין בספקים',
    'providers.showLess': 'הצג פחות',
    'providers.showAll': 'הצג הכל',
    'providers.selectedProvider': 'ספק נבחר',
    'providers.pricing': 'תמחור',
    'providers.contactForPricing': 'פנה לקבלת מחיר',
    'providers.realTime': 'זמן אמת',
    'providers.selected': 'נבחר',
    'providers.popularity': 'פופולריות',
    'providers.name': 'שם',
    'providers.price': 'מחיר',
    'providers.popular': 'פופולריים',
    'providers.all': 'הכל',
    'providers.totalProviders': 'סה״כ ספקים',
    'providers.sttProviders': 'ספקי דיבור לטקסט',
    'providers.llmProviders': 'ספקי מודל שפה',
    'providers.ttsProviders': 'ספקי טקסט לדיבור',
    'providers.noProvidersFound': 'לא נמצאו ספקים',
    'providers.tryDifferentFilters': 'נסה מסנני חיפוש שונים',
    'providers.clearFilters': 'נקה מסננים',
    'providers.searchProviders': 'חפש ספקים',
    'providers.configuration': 'הגדרות',
    'providers.selectProviderFirst': 'בחר ספק תחילה',
    'providers.apiKey': 'מפתח API',
    'providers.apiKeySecure': 'מפתח ה-API נשמר בצורה מאובטחת',
    'providers.basicSettings': 'הגדרות בסיסיות',
    'providers.required': 'חובה',
    'providers.advancedSettings': 'הגדרות מתקדמות',
    'providers.optional': 'אופציונלי',
    'providers.hideAdvanced': 'הסתר מתקדמות',
    'providers.showAdvanced': 'הצג מתקדמות',
    'providers.providerInfo': 'מידע על הספק',
    'providers.capabilities': 'יכולות',
    'providers.languages': 'שפות',
    'providers.testConnection': 'בדוק חיבור',
    'providers.configureProvider': 'הגדר ספק',

    // Builder
    'builder.pipelineBuilder': 'בנייה Drag-Drop',
    'builder.newPipeline': 'בנייה חדשה',
    'builder.defaultPipelineDescription': 'תיאור בנייה ברירת מחדל',
    'builder.pipelineInfo': 'מידע על הבנייה',
    'builder.nodes': 'רכיבים',
    'builder.connections': 'חיבורים',
    'builder.status': 'סטטוס',
    'builder.valid': 'תקין',
    'builder.invalid': 'לא תקין',
    'builder.incomplete': 'לא מושלם',
    'builder.validate': 'אמת',
    'builder.export': 'ייצא',
    'builder.reset': 'איפוס',
    'builder.save': 'שמור',
    'builder.confirmResetPipeline': 'האם אתה בטוח שברצונך לאפס את הבנייה?',
    'builder.speechToText': 'דיבור לטקסט',
    'builder.languageModel': 'מודל שפה',
    'builder.textToSpeech': 'טקסט לדיבור',
    'builder.sttDescription': 'המר דיבור לטקסט',
    'builder.llmDescription': 'עבד טקסט עם AI',
    'builder.ttsDescription': 'המר טקסט לדיבור',
    'builder.filter': 'מסנן',
    'builder.aggregator': 'צבירה',
    'builder.customFunction': 'פונקציה מותאמת',
    'builder.filterDescription': 'סנן נתונים',
    'builder.aggregatorDescription': 'צבור נתונים',
    'builder.customDescription': 'פונקציה מותאמת אישית',
    'builder.howToUse': 'איך להשתמש',
    'builder.dragInstructions': 'גרור רכיבים לקנבס',
    'builder.connectInstructions': 'חבר בין רכיבים',
    'builder.configureInstructions': 'הגדר כל רכיב',
    'builder.coreComponents': 'רכיבי ליבה',
    'builder.processingComponents': 'רכיבי עיבוד',
    'builder.tips': 'טיפים',
    'builder.tip1': 'התחל עם רכיבי הליבה',
    'builder.tip2': 'חבר לפי הסדר הנכון',
    'builder.tip3': 'בדוק את התצורה',

    // Common
    'common.back': 'חזור',

    // Voice Chat
    'voiceChat.title': 'ממשק שיחה קולית עם AI Voicei',
    'voiceChat.connectionStatus': 'מצב חיבור',
    'voiceChat.connected': 'מחובר',
    'voiceChat.connecting': 'מתחבר...',
    'voiceChat.disconnected': 'לא מחובר',
    'voiceChat.error': 'שגיאה',
    'voiceChat.selectCallType': 'בחרו סוג שיחה',
    'voiceChat.audioCall': 'שיחה קולית',
    'voiceChat.videoCall': 'שיחת וידאו',
    'voiceChat.audioOnly': 'שמע בלבד',
    'voiceChat.audioAndVideo': 'שמע ותמונה',
    'voiceChat.microphonePermission': 'תידרשו לאשר גישה למיקרופון בלבד',
    'voiceChat.cameraAndMicPermission': 'תידרשו לאשר גישה למצלמה ולמיקרופון',
    'voiceChat.clickToStart': 'לחצו על "התחל שיחה" להתחיל',
    'voiceChat.videoPreview': 'תצוגה מקדימה של הוידאו שלך',
    'voiceChat.enableVideo': 'הפעל וידאו',
    'voiceChat.enableCamera': 'הפעל מצלמה לשיחת וידאו',
    'voiceChat.startCall': 'התחל שיחה',
    'voiceChat.startAudioCall': 'התחל שיחה קולית',
    'voiceChat.startVideoCall': 'התחל שיחת וידאו',
    'voiceChat.endCall': 'סיים שיחה',
    'voiceChat.clickToStartCall': 'לחץ להתחלת שיחה עם AI Voicei',
    'voiceChat.smartVoiceService': 'שירות קולי חכם המבין עברית',
    'voiceChat.callActive': 'השיחה פעילה - דבר באופן טבעי',
    'voiceChat.speakingWithAI': 'מדבר עברית עם Gemini AI',
    'voiceChat.connectedToService': 'מחובר לשירות AI Voicei',
    'voiceChat.connectingToService': 'מתחבר לשירות AI Voicei...',
    'voiceChat.connectionError': 'שגיאת חיבור',
    'voiceChat.notConnected': 'לא מחובר לשירות',
    'voiceChat.sessionActive': 'השיחה פעילה',

    // Layout
    'layout.searchPlaceholder': 'חפש סוכנים, תבניות, או תיעוד...',

    // Conversation History
    'conversationHistory.you': 'אתה',
    'conversationHistory.system': 'מערכת',
    'conversationHistory.aiVoice': 'AI Voicei',

    // Build with Agenty
    'buildWithAgenty.title': 'בנה עם אגנטי',
    'buildWithAgenty.description': 'צור סוכנים עם סיוע AI באמצעות הנחיות פשוטות',
    'buildWithAgenty.tryAIBuilder': 'נסה בונה AI',
    'buildWithAgenty.subtitle': 'תאר את הסוכן שאתה רוצה, ואנחנו ניצור אותו בשבילך',
    'buildWithAgenty.describeYourAgent': 'תאר את הסוכן שלך',
    'buildWithAgenty.describeYourAgentDesc': 'ספר לנו מה הסוכן שלך צריך לעשות, וקלוד ישאל כמה שאלות הבהרה',
    'buildWithAgenty.agentDescription': 'תיאור הסוכן',
    'buildWithAgenty.descriptionPlaceholder': 'לדוגמה: אני צריך סוכן שירות לקוחות שעונה על שאלות בעברית על המוצרים שלנו...',
    'buildWithAgenty.agentName': 'שם הסוכן',
    'buildWithAgenty.namePlaceholder': 'לדוגמה: סוכן שירות לקוחות',
    'buildWithAgenty.language': 'שפה',
    'buildWithAgenty.languagePlaceholder': 'עברית, English, etc.',
    'buildWithAgenty.knowledgeBase': 'בסיס ידע',
    'buildWithAgenty.uploadDocument': 'העלה מסמך (PDF, TXT, DOC, MD)',
    'buildWithAgenty.processing': 'מעבד...',
    'buildWithAgenty.generateAgent': 'צור סוכן עם AI',
    'buildWithAgenty.clarificationQuestions': 'שאלות הבהרה',
    'buildWithAgenty.clarificationDesc': 'קלוד שואל כמה שאלות כדי ליצור את הסוכן המושלם',
    'buildWithAgenty.typeYourAnswer': 'הקלד את התשובה שלך...',
    'buildWithAgenty.send': 'שלח',
    'buildWithAgenty.generatingYourAgent': 'יוצר את הסוכן שלך...',
    'buildWithAgenty.generatingDesc': 'קלוד מנתח את הדרישות ויוצר את הסוכן המושלם',
    'buildWithAgenty.analyzingRequirements': 'מנתח דרישות',
    'buildWithAgenty.generatingSystemMessage': 'יוצר הודעת מערכת',
    'buildWithAgenty.configuringProviders': 'מגדיר ספקים',
    'buildWithAgenty.finalizingAgent': 'מסיים את הסוכן',
    'buildWithAgenty.agentCreated': 'הסוכן נוצר בהצלחה!',
    'buildWithAgenty.agentCreatedDesc': 'הסוכן שלך מוכן. אתה יכול לערוך אותו, להוסיף מפתחות API ולבדוק אותו',
    'buildWithAgenty.viewAgent': 'צפה בסוכן',

    // Build with Agenty - New Magical Flow
    'buildWithAgenty.welcome': 'שלום!',
    'buildWithAgenty.welcomeIntro': 'אני Agenty, בואו ניצור את הסוכן המושלם שלכם!',
    'buildWithAgenty.welcomeSubtitle': 'אספר לי מה אתה רוצה, ואני אבנה עבורך סוכן AI מותאם אישית תוך דקות',
    'buildWithAgenty.letsGetStarted': 'בואו נתחיל!',
    'buildWithAgenty.whatShouldAgentDo': 'מה הסוכן שלך צריך לעשות?',
    'buildWithAgenty.whatsAgentName': 'איך נקרא לסוכן שלך?',
    'buildWithAgenty.whatLanguage': 'באיזו שפה הסוכן צריך לדבר?',
    'buildWithAgenty.whichVoice': 'איזה קול לסוכן?',
    'buildWithAgenty.anyDocuments': 'יש לך מסמכים לסוכן?',
    'buildWithAgenty.femaleVoice': 'נקבה',
    'buildWithAgenty.maleVoice': 'זכר',
    'buildWithAgenty.voiceAffects': 'בחירה זו משפיעה על הקול בזמן אמת של הסוכן',
    'buildWithAgenty.uploadDoc': 'העלה מסמך',
    'buildWithAgenty.pdfTxtDoc': 'PDF, TXT, DOC, או MD',
    'buildWithAgenty.optionalDocs': '(אופציונלי - הסוכן יוכל ללמוד ממסמכים אלה)',
    'buildWithAgenty.optionalName': '(אופציונלי - נוכל להמליץ על שם מתאים)',
    'buildWithAgenty.optionalLanguage': '(אופציונלי - ברירת המחדל היא אנגלית)',
    'buildWithAgenty.createAgent': 'צור סוכן!',
    'buildWithAgenty.continue': 'המשך',
    'buildWithAgenty.back': 'חזור',
    'buildWithAgenty.characters': 'תווים',
    'buildWithAgenty.beDetailed': 'תאר בפירוט ככל האפשר',
    'buildWithAgenty.fewQuestions': 'יש לי כמה שאלות...',
    'buildWithAgenty.craftingPersonality': 'יוצר אישיות',
    'buildWithAgenty.connectingServices': 'מתחבר לשירותי AI',
    'buildWithAgenty.agentReady': 'הסוכן מוכן',
    'buildWithAgenty.yourAgentBorn': 'הסוכן שלך נולד!',
    'buildWithAgenty.meet': 'פגוש את',
    'buildWithAgenty.readyToGo': 'הסוכן שלך מוכן לפעולה! בוא נראה מה הוא יכול לעשות.',
    'buildWithAgenty.agents': 'סוכנים',
    'buildWithAgenty.ready': 'מוכן',
    'buildWithAgenty.power': 'עוצמה',
    'buildWithAgenty.max': 'Max',

    // Dashboard
    'dashboard.title': 'לוח בקרה',
    'dashboard.welcome': 'ברוכים הבאים לאגנטי',
    'dashboard.monitorAgents': 'עקוב אחר הסוכנים שלך ומדד ביצועים',
    'dashboard.satisfaction': 'שביעות רצון',
    'dashboard.avgResponseTime': 'זמן תגובה ממוצע',
    'dashboard.conversations': 'שיחות',
    'dashboard.totalAgents': 'סך כל הסוכנים',
    'dashboard.fromLastMonth': 'מהחודש שעבר',
    'dashboard.improvement': 'שיפור',
    'dashboard.viewAll': 'צפה בהכל',
    'dashboard.yourAgents': 'הסוכנים שלך',
    'dashboard.manageAndMonitor': 'נהל ועקוב אחר סוכני הקול של AI',
    'dashboard.customerSupportBot': 'בוט תמיכת לקוחות',
    'dashboard.salesAssistant': 'עוזר מכירות',
    'dashboard.hebrewSupportBot': 'בוט תמיכה עברית',
    'dashboard.conversations_': 'שיחות',
    'dashboard.quickActions': 'פעולות מהירות',
    'dashboard.getStartedCommon': 'התחל עם משימות נפוצות',
    'dashboard.viewAnalytics': 'צפה בניתוחים',
    'dashboard.browseTemplates': 'עיין בתבניות',
    'dashboard.createNewAgent': 'צור סוכן חדש',
    'dashboard.testAgent': 'בדוק סוכן',
    'dashboard.quickTest': 'בדיקה מהירה',
    'dashboard.quickTestDesc': 'בדיקה מהירה עם Gemini Live',
    'dashboard.active': 'פעיל',
    'dashboard.inactive': 'לא פעיל',
    'dashboard.paused': 'מושהה',

    // Pricing
    'pricing.choosePlan': 'בחר את התוכנית המתאימה לך',
    'pricing.choosePlanDesc': 'התחל בחינם או שדרג לגישה לכל התכונות',
    'pricing.free': 'חינם',
    'pricing.perMonth': '/ לחודש',
    'pricing.mostPopular': 'הפופולרית ביותר',
    'pricing.limitations': 'מגבלות',
    'pricing.getStarted': 'התחל',
    'pricing.upgradeTo': 'שדרג ל',
    'pricing.contactUs': 'צור קשר',
    'pricing.pricingNote': 'כל התוכניות כוללות גישה למקורות הידע ולעדכונים השוטפים',
    'pricing.needCustomPlan': 'צריך תוכנית מותאמת אישית לעסק?',

    // Free Plan
    'pricing.freePlan': 'תוכנית חינמית',
    'pricing.freePlanDesc': 'מושלם להתחלה ולחקור את הפלטפורמה',
    'pricing.freeFeature1': 'יצירת עד 3 סוכנים',
    'pricing.freeFeature2': 'גישה לתבניות',
    'pricing.freeFeature3': 'בדיקות דמו עם מגבלות',
    'pricing.freeFeature4': 'אנליטיקס בסיסי',
    'pricing.freeFeature5': 'תמיכת קהילה',
    'pricing.freeLimitation1': 'מוגבל ל-1,000 שיחות לחודש',
    'pricing.freeLimitation2': 'ספקים בסיסיים בלבד',

    // Standard Plan
    'pricing.standardPlan': 'תוכנית סטנדרט',
    'pricing.standardPlanDesc': 'לעסקים קטנים ובינוניים',
    'pricing.standardFeature1': 'סוכנים ללא הגבלה',
    'pricing.standardFeature2': 'כל ספקי ה-AI (40+)',
    'pricing.standardFeature3': 'אנליטיקס מתקדם',
    'pricing.standardFeature4': 'תמיכה בעדיפות',
    'pricing.standardFeature5': 'גישה ל-API',
    'pricing.standardFeature6': 'שיתוף פעולה צוותי (עד 5 משתמשים)',
    'pricing.standardFeature7': 'מיתוג מותאם',
    'pricing.standardFeature8': '50,000 שיחות לחודש',

    // Pro Plan
    'pricing.proPlan': 'תוכנית Pro',
    'pricing.proPlanDesc': 'לארגונים גדולים ושותפים',
    'pricing.proFeature1': 'כל מה שיש ב-Standard',
    'pricing.proFeature2': 'פלטפורמת White-label',
    'pricing.proFeature3': 'תמיכה בדומיין מותאם',
    'pricing.proFeature4': 'מנהל חשבון ייעודי',
    'pricing.proFeature5': 'סיוע ביצירת סוכנים',
    'pricing.proFeature6': 'חברי צוות ללא הגבלה',
    'pricing.proFeature7': 'שיחות ללא הגבלה',
    'pricing.proFeature8': 'ערבות SLA',
    'pricing.proFeature9': 'אינטגרציות מותאמות',
    'pricing.proFeature10': 'אפשרויות חלוקת הכנסות',

    // Pipeline Builder
    'builder.pipelineBuilder': 'בונה צינור',
    'builder.speechToText': 'דיבור לטקסט',
    'builder.languageModel': 'מודל שפה',
    'builder.textToSpeech': 'טקסט לדיבור',
    'builder.filter': 'מסנן',
    'builder.aggregator': 'מצרף',
    'builder.customFunction': 'פונקציה מותאמת',
    'builder.sttDescription': 'המר דיבור לטקסט',
    'builder.llmDescription': 'עבד והבן טקסט',
    'builder.ttsDescription': 'המר טקסט לדיבור',
    'builder.filterDescription': 'סנן ועבד נתונים',
    'builder.aggregatorDescription': 'צרף ושלב נתונים',
    'builder.customDescription': 'פונקצית עיבוד מותאמת',
    'builder.valid': 'תקין',
    'builder.invalid': 'לא תקין',
    'builder.validate': 'אמת',
    'builder.export': 'ייצא',
    'builder.reset': 'איפוס',
    'builder.save': 'שמור',
    'builder.pipelineInfo': 'מידע צינור',
    'builder.nodes': 'צמתים',
    'builder.connections': 'חיבורים',
    'builder.status': 'מצב',
    'builder.incomplete': 'לא הושלם',
    'builder.howToUse': 'איך להשתמש',
    'builder.dragInstructions': 'גרור רכיבים מסרגל הכלים לקנבס',
    'builder.connectInstructions': 'חבר רכיבים על ידי גרירה מיציאה לכניסה',
    'builder.configureInstructions': 'לחץ על רכיבים כדי לקבוע הגדרות',
    'builder.coreComponents': 'רכיבי ליבה',
    'builder.processingComponents': 'רכיבי עיבוד',
    'builder.tips': 'עצות',
    'builder.tip1': 'התחל עם STT → LLM → TTS לסוכן קול בסיסי',
    'builder.tip2': 'הוסף מסננים ומצרפים לעיבוד מתקדם',
    'builder.tip3': 'אמת את הצינור שלך לפני השמירה',
    'builder.nodeConfiguration': 'הגדרת צומת',
    'builder.basicInformation': 'מידע בסיסי',
    'builder.nodeLabel': 'תווית צומת',
    'builder.nodeType': 'סוג צומת',
    'builder.nodeId': 'מזהה צומת',
    'builder.enterNodeLabel': 'הכנס תווית צומת',
    'builder.providerSelection': 'בחירת ספק',
    'builder.providerConfiguration': 'הגדרת ספק',
    'builder.configurationStatus': 'מצב הגדרה',
    'builder.fullyConfigured': 'מוגדר במלואו',
    'builder.requiresConfiguration': 'דורש הגדרה',
    'builder.saveConfiguration': 'שמור הגדרה',
    'builder.confirmDeleteNode': 'האם אתה בטוח שברצונך למחוק צומת זה?',
    'builder.confirmResetPipeline': 'האם אתה בטוח שברצונך לאפס את הצינור? כל השינויים יאבדו.',
    'builder.noConfigurationAvailable': 'אין הגדרה זמינה לסוג צומת זה',
    'builder.newPipeline': 'צינור חדש',
    'builder.defaultPipelineDescription': 'צינור חדש לבניית סוכני קול AI',

    // Marketplace
    'marketplace.title': 'חנות סוכנים',
    'marketplace.description': 'גלה, שתף והתקן סוכני AI שנוצרו על ידי הקהילה',
    'marketplace.publishAgent': 'פרסם סוכן',
    'marketplace.searchPlaceholder': 'חפש סוכנים, קטגוריות או תכונות...',
    'marketplace.allCategories': 'כל הקטגוריות',
    'marketplace.mostPopular': 'הכי פופולריים',
    'marketplace.newest': 'החדשים ביותר',
    'marketplace.highestRated': 'בעלי הדירוג הגבוה ביותר',
    'marketplace.mostDownloaded': 'הכי הורדו',
    'marketplace.discover': 'גלה',
    'marketplace.featured': 'מומלצים',
    'marketplace.trending': 'טרנדים',
    'marketplace.myAgents': 'הסוכנים שלי',
    'marketplace.noAgentsFound': 'לא נמצאו סוכנים',
    'marketplace.tryAdjustCriteria': 'נסה להתאים את קריטריוני החיפוש או לעיין בקטגוריות שונות',
    'marketplace.clearFilters': 'נקה מסננים',
    'marketplace.shareYourAgents': 'שתף את הסוכנים שלך',
    'marketplace.publishToMarketplace': 'פרסם את הסוכנים שלך לחנות ועזור לקהילה',
    'marketplace.publishFirstAgent': 'פרסם את הסוכן הראשון שלך',
    'marketplace.by': 'מאת',
    'marketplace.premium': 'פרימיום',
    'marketplace.free': 'חינם',
    'marketplace.rating': 'דירוג',
    'marketplace.downloads': 'הורדות',
    'marketplace.activeUsers': 'משתמשים פעילים',
    'marketplace.responseTime': 'זמן תגובה',
    'marketplace.addToAgents': 'הוסף לסוכנים',
    'marketplace.adding': 'מוסיף...',
    'marketplace.addedSuccess': 'סוכן נוסף בהצלחה!',
    'marketplace.addedDescription': 'נוסף לסוכנים שלך.',
    'marketplace.addFailed': 'הוספת סוכן נכשלה',
    'marketplace.tryAgainLater': 'אנא נסה שוב מאוחר יותר.',
    'marketplace.backToMarketplace': 'חזור לחנות',
    'marketplace.about': 'אודות',
    'marketplace.keyFeatures': 'תכונות מפתח',
    'marketplace.performanceMetrics': 'מדדי ביצועים',
    'marketplace.totalConversations': 'סך כל השיחות',
    'marketplace.customerSatisfaction': 'שביעות רצון לקוחות',
    'marketplace.category': 'קטגוריה',
    'marketplace.aiProviders': 'ספקי AI',
    'marketplace.servicesUsed': 'שירותים בשימוש',
    'marketplace.supportedLanguages': 'שפות נתמכות',
    'marketplace.configuration': 'תצורה',
    'marketplace.reviews': 'ביקורות',
    'marketplace.changelog': 'יומן שינויים',
    'marketplace.overview': 'סקירה',
    'marketplace.noReviewsYet': 'אין ביקורות עדיין',
    'marketplace.firstToReview': 'היה הראשון לבקר סוכן זה',
    'marketplace.latestUpdate': 'עדכון אחרון',
    'marketplace.performanceImprovements': 'שיפורי ביצועים',
    'marketplace.bugFixes': 'תיקוני באגים ושיפורי יציבות',
    'marketplace.conversations': 'שיחות',
    'marketplace.response': 'תגובה',
    'marketplace.users': 'משתמשים',
    'marketplace.addToYourAgents': 'הוסף לסוכנים שלך',
    'marketplace.customerService': 'שירות לקוחות',
    'marketplace.ecommerce': 'מסחר אלקטרוני',
    'marketplace.healthcare': 'בריאות',
    'marketplace.education': 'חינוך',
    'marketplace.finance': 'כספים',
    'marketplace.entertainment': 'בידור',
    'marketplace.productivity': 'פרודוקטיביות',

    // Agents
    'agents.agents': 'סוכנים',
    'agents.createAgent': 'צור סוכן',
    'agents.createNewAgent': 'צור סוכן חדש',
    'agents.editAgent': 'ערוך סוכן',
    'agents.manageYourAgents': 'נהל את הסוכנים שלך',
    'agents.basicInformation': 'מידע בסיסי',
    'agents.basicInformationDesc': 'מידע כללי על הסוכן שלך',
    'agents.aiConfiguration': 'הגדרות AI',
    'agents.aiConfigurationDesc': 'הגדר את שירותי ה-AI לסוכן שלך',
    'agents.agentName': 'שם הסוכן',
    'agents.enterAgentName': 'הזן שם לסוכן',
    'agents.description': 'תיאור',
    'agents.enterDescription': 'הזן תיאור לסוכן',
    'agents.status': 'מצב',
    'agents.deploymentType': 'סוג פריסה',
    'agents.selectStatus': 'בחר מצב',
    'agents.selectDeploymentType': 'בחר סוג פריסה',
    'agents.draft': 'טיוטה',
    'agents.webRTC': 'WebRTC',
    'agents.phoneCall': 'שיחת טלפון',
    'agents.whatsApp': 'וואטסאפ',
    'agents.apiOnly': 'API בלבד',
    'agents.speechToText': 'דיבור לטקסט',
    'agents.languageModel': 'מודל שפה',
    'agents.textToSpeech': 'טקסט לדיבור',
    'agents.systemPrompt': 'הנחיה מערכת',
    'agents.enterSystemPrompt': 'הזן הנחיית מערכת',
    'agents.systemPromptDesc': 'ההנחיות שהסוכן יקבל',
    'agents.provider': 'ספק',
    'agents.model': 'מודל',
    'agents.language': 'שפה',
    'agents.voice': 'קול',
    'agents.temperature': 'טמפרטורה',
    'agents.maxTokens': 'מקסימום אסימונים',
    'agents.saving': 'שומר...',
    'agents.saveChanges': 'שמור שינויים',
    'agents.creating': 'יוצר...',
    'agents.configureYourAgent': 'הגדר את הסוכן שלך',
    'agents.useTemplate': 'השתמש בתבנית',
    'agents.editingAgent': 'עורך סוכן',
    'agents.nameRequired': 'שם הסוכן נדרש',
    'agents.descriptionRequired': 'תיאור נדרש',
    'agents.systemPromptRequired': 'הנחיית מערכת נדרשת',
    'agents.agentNotFound': 'סוכן לא נמצא',
    'agents.agentNotFoundDesc': 'הסוכן שחיפשת לא קיים במערכת',
    'agents.backToAgents': 'חזור לסוכנים',
    'agents.overview': 'סקירה',
    'agents.analytics': 'ניתוחים',
    'agents.configuration': 'הגדרות',
    'agents.totalConversations': 'סך כל השיחות',
    'agents.activeToday': 'פעיל היום',
    'agents.template': 'תבנית',
    'agents.created': 'נוצר',
    'agents.lastUpdated': 'עודכן לאחרונה',
    'agents.test': 'בדוק',
    'agents.edit': 'ערוך',
    'agents.duplicate': 'שכפל',
    'agents.deploy': 'פרוס',
    'agents.stop': 'עצור',
    'agents.confirmDelete': 'האם אתה בטוח שברצונך למחוק את הסוכן?',
    'agents.searchAgents': 'חפש סוכנים',
    'agents.filterByStatus': 'סנן לפי מצב',
    'agents.allStatuses': 'כל הסטטוסים',
    'agents.sortBy': 'מיין לפי',
    'agents.name': 'שם',
    'agents.noAgentsFound': 'לא נמצאו סוכנים',
    'agents.noAgentsYet': 'עדיין אין לך סוכנים',
    'agents.tryAdjustingFilters': 'נסה לשנות את המסננים',
    'agents.createFirstAgent': 'צור את הסוכן הראשון שלך',
    'agents.advancedConfiguration': 'הגדרות מתקדמות',
    'agents.advancedConfigurationDesc': 'התאם אישיות קול, טיפול בהפרעות, ניהול הקשר ועוד',

    // Templates
    'templates.agentTemplates': 'תבניות סוכנים',
    'templates.chooseTemplate': 'בחר תבנית כדי להתחיל במהירות',
    'templates.popularTemplates': 'תבניות פופולריות',
    'templates.mostUsedTemplates': 'התבניות הנפוצות ביותר בקהילה',
    'templates.searchTemplates': 'חפש תבניות',
    'templates.filterByCategory': 'סנן לפי קטגוריה',
    'templates.allCategories': 'כל הקטגוריות',
    'templates.sortBy': 'מיין לפי',
    'templates.popular': 'פופולרי',
    'templates.rating': 'דירוג',
    'templates.recent': 'אחרון',
    'templates.name': 'שם',
    'templates.all': 'הכל',
    'templates.noTemplatesFound': 'לא נמצאו תבניות',
    'templates.tryAdjustingFilters': 'נסה לשנות את המסננים',
    'templates.clearFilters': 'נקה מסננים',
    'templates.useTemplate': 'השתמש בתבנית',
    'templates.customerService': 'שירות לקוחות',
    'templates.sales': 'מכירות',
    'templates.hospitality': 'אירוח',
    'templates.ecommerce': 'מסחר אלקטרוני',
    'templates.healthcare': 'בריאות',
    'templates.education': 'חינוך',
    'templates.finance': 'פיננסים',
    'templates.general': 'כללי',
    'templates.preview': 'תצוגה מקדימה',
    'templates.description': 'תיאור',
    'templates.configuration': 'הגדרות',
    'templates.aiConfiguration': 'הגדרות AI',
    'templates.templateInfo': 'מידע על התבנית',
    'templates.category': 'קטגוריה',
    'templates.deploymentOptions': 'אפשרויות פריסה',
    'templates.tags': 'תגיות',
    'templates.createdBy': 'נוצר על ידי',
    'templates.lastUpdated': 'עודכן לאחרונה',
    'templates.actions': 'פעולות',
    'templates.previewTemplate': 'תצוגה מקדימה של התבנית',
    'templates.customizeTemplate': 'התאמה אישית של התבנית',
    'templates.similarTemplates': 'תבניות דומות',
    'templates.noSimilarTemplates': 'אין תבניות דומות',
    'templates.templateNotFound': 'התבנית לא נמצאה',
    'templates.templateNotFoundDesc': 'התבנית שחיפשת לא קיימת במערכת',
    'templates.backToTemplates': 'חזור לתבניות',
    'templates.uses': 'שימושים',

    // Common
    'common.back': 'חזור',
    'common.cancel': 'בטל',
    'common.save': 'שמור',
    'common.edit': 'ערוך',
    'common.delete': 'מחק',
    'common.optional': 'אופציונלי'
  },
  en: {
    // Navigation
    'navigation.dashboard': 'Dashboard',
    'navigation.myAgents': 'My Agents',
    'navigation.pipelineBuilder': 'Drag-Drop Builder',
    'navigation.agentMarketplace': 'Agent Marketplace',
    'navigation.providerMarketplace': 'Providers',
    'navigation.analytics': 'Analytics',
    'navigation.templates': 'Templates',
    'navigation.whiteLabel': 'White Label',
    'navigation.settings': 'Settings',
    'navigation.createAgent': 'Create Agent',

    // Agent Creation
    'agents.buildAgentDesc': 'Create an agent using advanced drag-drop builder',
    'agents.createNewAgent': 'Create New Agent',
    'agents.agentName': 'Agent Name',
    'agents.description': 'Description',
    'agents.systemPrompt': 'System Prompt',
    'agents.enterAgentName': 'Enter agent name',
    'agents.enterDescription': 'Enter description',
    'agents.enterSystemPrompt': 'Enter system prompt',
    'agents.systemPromptDesc': 'This prompt will define your agent behavior',
    'agents.basicInformation': 'Basic Information',
    'agents.basicInfoDesc': 'Set up the basic details of your agent',
    'agents.selectProviders': 'Select Providers',
    'agents.buildPipeline': 'Build Pipeline',
    'agents.agentSummary': 'Agent Summary',
    'agents.testAgent': 'Test Agent',
    'agents.speechToText': 'Speech to Text',
    'agents.languageModel': 'Language Model',
    'agents.textToSpeech': 'Text to Speech',
    'agents.selectSTTProvider': 'Select Speech to Text provider',
    'agents.selectLLMProvider': 'Select Language Model provider',
    'agents.selectTTSProvider': 'Select Text to Speech provider',
    'agents.selectRealtimeProvider': 'Select realtime speech provider',
    'agents.realtimeSpeech': 'Realtime Speech',
    'agents.individualProviders': 'Individual Providers',
    'agents.configuration': 'Configuration',
    'agents.testYourAgent': 'Test Your Agent',
    'agents.testAgentDesc': 'Test your agent before deployment',
    'agents.notSelected': 'Not selected',
    'agents.transport': 'Transport',
    'agents.backToAgents': 'Back to Agents',
    'agents.startTest': 'Start Test',
    'agents.startingTest': 'Starting test...',
    'agents.progress': 'Progress',
    'agents.next': 'Next',
    'agents.previous': 'Previous',
    'agents.saveAgent': 'Save Agent',
    'agents.saving': 'Saving...',
    'agents.testing': 'Testing...',
    'agents.nameRequired': 'Agent name is required',
    'agents.sttProviderRequired': 'Speech to Text provider is required',
    'agents.llmProviderRequired': 'Language Model provider is required',
    'agents.ttsProviderRequired': 'Text to Speech provider is required',
    'agents.sttApiKeyRequired': 'Speech to Text API key is required',
    'agents.llmApiKeyRequired': 'Language Model API key is required',
    'agents.ttsApiKeyRequired': 'Text to Speech API key is required',

    // Providers
    'providers.providerMarketplace': 'AI Providers',
    'providers.chooseFromProviders': 'Choose from',
    'providers.aiProviders': 'AI providers',
    'providers.selectProvider': 'Select Provider',
    'providers.selectProviderDesc': 'Choose a suitable AI provider',
    'providers.selectSTTProvider': 'Select Speech to Text provider',
    'providers.selectLLMProvider': 'Select Language Model provider',
    'providers.selectTTSProvider': 'Select Text to Speech provider',
    'providers.sttProviderDesc': 'Speech to text conversion provider',
    'providers.llmProviderDesc': 'Advanced language model provider',
    'providers.ttsProviderDesc': 'Text to speech conversion provider',
    'providers.realtimeProviderDesc': 'Real-time speech-to-speech conversation provider',
    'providers.selectRealtimeProvider': 'Select realtime speech provider',
    'providers.quickSelect': 'Quick Select',
    'providers.chooseProvider': 'Choose Provider',
    'providers.browseProviders': 'Browse Providers',
    'providers.showLess': 'Show Less',
    'providers.showAll': 'Show All',
    'providers.selectedProvider': 'Selected Provider',
    'providers.pricing': 'Pricing',
    'providers.contactForPricing': 'Contact for pricing',
    'providers.realTime': 'Real-time',
    'providers.selected': 'Selected',
    'providers.popularity': 'Popularity',
    'providers.name': 'Name',
    'providers.price': 'Price',
    'providers.popular': 'Popular',
    'providers.all': 'All',
    'providers.totalProviders': 'Total Providers',
    'providers.sttProviders': 'Speech to Text Providers',
    'providers.llmProviders': 'Language Model Providers',
    'providers.ttsProviders': 'Text to Speech Providers',
    'providers.noProvidersFound': 'No providers found',
    'providers.tryDifferentFilters': 'Try different search filters',
    'providers.clearFilters': 'Clear Filters',
    'providers.searchProviders': 'Search providers',
    'providers.configuration': 'Configuration',
    'providers.selectProviderFirst': 'Select a provider first',
    'providers.apiKey': 'API Key',
    'providers.apiKeySecure': 'Your API key is stored securely',
    'providers.basicSettings': 'Basic Settings',
    'providers.required': 'Required',
    'providers.advancedSettings': 'Advanced Settings',
    'providers.optional': 'Optional',
    'providers.hideAdvanced': 'Hide Advanced',
    'providers.showAdvanced': 'Show Advanced',
    'providers.providerInfo': 'Provider Info',
    'providers.capabilities': 'Capabilities',
    'providers.languages': 'Languages',
    'providers.testConnection': 'Test Connection',
    'providers.configureProvider': 'Configure Provider',

    // Builder
    'builder.pipelineBuilder': 'Drag-Drop Builder',
    'builder.newPipeline': 'New Pipeline',
    'builder.defaultPipelineDescription': 'Default pipeline description',
    'builder.pipelineInfo': 'Pipeline Info',
    'builder.nodes': 'Nodes',
    'builder.connections': 'Connections',
    'builder.status': 'Status',
    'builder.valid': 'Valid',
    'builder.invalid': 'Invalid',
    'builder.incomplete': 'Incomplete',
    'builder.validate': 'Validate',
    'builder.export': 'Export',
    'builder.reset': 'Reset',
    'builder.save': 'Save',
    'builder.confirmResetPipeline': 'Are you sure you want to reset the pipeline?',
    'builder.speechToText': 'Speech to Text',
    'builder.languageModel': 'Language Model',
    'builder.textToSpeech': 'Text to Speech',
    'builder.sttDescription': 'Convert speech to text',
    'builder.llmDescription': 'Process text with AI',
    'builder.ttsDescription': 'Convert text to speech',
    'builder.filter': 'Filter',
    'builder.aggregator': 'Aggregator',
    'builder.customFunction': 'Custom Function',
    'builder.filterDescription': 'Filter data',
    'builder.aggregatorDescription': 'Aggregate data',
    'builder.customDescription': 'Custom function',
    'builder.howToUse': 'How to Use',
    'builder.dragInstructions': 'Drag components to canvas',
    'builder.connectInstructions': 'Connect components together',
    'builder.configureInstructions': 'Configure each component',
    'builder.coreComponents': 'Core Components',
    'builder.processingComponents': 'Processing Components',
    'builder.tips': 'Tips',
    'builder.tip1': 'Start with core components',
    'builder.tip2': 'Connect in the right order',
    'builder.tip3': 'Test your configuration',

    // Common
    'common.back': 'Back',

    // Voice Chat
    'voiceChat.title': 'AI Voice Interface',
    'voiceChat.connectionStatus': 'Connection Status',
    'voiceChat.connected': 'Connected',
    'voiceChat.connecting': 'Connecting...',
    'voiceChat.disconnected': 'Disconnected',
    'voiceChat.error': 'Error',
    'voiceChat.selectCallType': 'Select Call Type',
    'voiceChat.audioCall': 'Audio Call',
    'voiceChat.videoCall': 'Video Call',
    'voiceChat.audioOnly': 'Audio only',
    'voiceChat.audioAndVideo': 'Audio and video',
    'voiceChat.microphonePermission': 'Microphone permission required only',
    'voiceChat.cameraAndMicPermission': 'Camera and microphone permissions required',
    'voiceChat.clickToStart': 'Click "Start Call" to begin',
    'voiceChat.videoPreview': 'Your video preview',
    'voiceChat.enableVideo': 'Enable Video',
    'voiceChat.enableCamera': 'Enable camera for video call',
    'voiceChat.startCall': 'Start Call',
    'voiceChat.startAudioCall': 'Start Audio Call',
    'voiceChat.startVideoCall': 'Start Video Call',
    'voiceChat.endCall': 'End Call',
    'voiceChat.clickToStartCall': 'Click to start call with AI Voice',
    'voiceChat.smartVoiceService': 'Smart voice service that understands English',
    'voiceChat.callActive': 'Call active - speak naturally',
    'voiceChat.speakingWithAI': 'Speaking English with Gemini AI',
    'voiceChat.connectedToService': 'Connected to AI Voice service',
    'voiceChat.connectingToService': 'Connecting to AI Voice service...',
    'voiceChat.connectionError': 'Connection error',
    'voiceChat.notConnected': 'Not connected to service',
    'voiceChat.sessionActive': 'Session Active',

    // Layout
    'layout.searchPlaceholder': 'Search agents, templates, or documentation...',

    // Conversation History
    'conversationHistory.you': 'You',
    'conversationHistory.system': 'System',
    'conversationHistory.aiVoice': 'AI Voice',

    // Build with Agenty
    'buildWithAgenty.title': 'Build with Agenty',
    'buildWithAgenty.description': 'Create agents with AI assistance using simple prompts',
    'buildWithAgenty.tryAIBuilder': 'Try AI Builder',
    'buildWithAgenty.subtitle': 'Describe the agent you want, and we\'ll create it for you',
    'buildWithAgenty.describeYourAgent': 'Describe Your Agent',
    'buildWithAgenty.describeYourAgentDesc': 'Tell us what your agent should do, and Claude will ask clarifying questions',
    'buildWithAgenty.agentDescription': 'Agent Description',
    'buildWithAgenty.descriptionPlaceholder': 'For example: I need a customer service agent that answers questions in English about our products...',
    'buildWithAgenty.agentName': 'Agent Name',
    'buildWithAgenty.namePlaceholder': 'For example: Customer Service Agent',
    'buildWithAgenty.language': 'Language',
    'buildWithAgenty.languagePlaceholder': 'English, עברית, etc.',
    'buildWithAgenty.knowledgeBase': 'Knowledge Base',
    'buildWithAgenty.uploadDocument': 'Upload document (PDF, TXT, DOC, MD)',
    'buildWithAgenty.processing': 'Processing...',
    'buildWithAgenty.generateAgent': 'Generate Agent with AI',
    'buildWithAgenty.clarificationQuestions': 'Clarification Questions',
    'buildWithAgenty.clarificationDesc': 'Claude is asking a few questions to create the perfect agent',
    'buildWithAgenty.typeYourAnswer': 'Type your answer...',
    'buildWithAgenty.send': 'Send',
    'buildWithAgenty.generatingYourAgent': 'Generating Your Agent...',
    'buildWithAgenty.generatingDesc': 'Claude is analyzing your requirements and creating the perfect agent',
    'buildWithAgenty.analyzingRequirements': 'Analyzing requirements',
    'buildWithAgenty.generatingSystemMessage': 'Generating system message',
    'buildWithAgenty.configuringProviders': 'Configuring providers',
    'buildWithAgenty.finalizingAgent': 'Finalizing agent',
    'buildWithAgenty.agentCreated': 'Agent Created Successfully!',
    'buildWithAgenty.agentCreatedDesc': 'Your agent is ready. You can edit it, add API keys, and test it',
    'buildWithAgenty.viewAgent': 'View Agent',

    // Build with Agenty - New Magical Flow
    'buildWithAgenty.welcome': 'Hello!',
    'buildWithAgenty.welcomeIntro': "I'm Agenty, let's create your perfect agent!",
    'buildWithAgenty.welcomeSubtitle': "Tell me what you want, and I'll build you a custom AI agent in minutes",
    'buildWithAgenty.letsGetStarted': "Let's Get Started!",
    'buildWithAgenty.whatShouldAgentDo': 'What should your agent do?',
    'buildWithAgenty.whatsAgentName': "What's your agent's name?",
    'buildWithAgenty.whatLanguage': 'What language should your agent speak?',
    'buildWithAgenty.whichVoice': 'Which voice for your agent?',
    'buildWithAgenty.anyDocuments': 'Any documents for your agent?',
    'buildWithAgenty.femaleVoice': 'Female',
    'buildWithAgenty.maleVoice': 'Male',
    'buildWithAgenty.voiceAffects': "This affects your agent's real-time voice",
    'buildWithAgenty.uploadDoc': 'Upload a document',
    'buildWithAgenty.pdfTxtDoc': 'PDF, TXT, DOC, or MD',
    'buildWithAgenty.optionalDocs': '(Optional - agent will learn from these documents)',
    'buildWithAgenty.optionalName': '(Optional - we can suggest a name)',
    'buildWithAgenty.optionalLanguage': '(Optional - defaults to English)',
    'buildWithAgenty.createAgent': 'Create Agent!',
    'buildWithAgenty.continue': 'Continue',
    'buildWithAgenty.back': 'Back',
    'buildWithAgenty.characters': 'characters',
    'buildWithAgenty.beDetailed': 'Be as detailed as possible',
    'buildWithAgenty.fewQuestions': 'I have a few questions...',
    'buildWithAgenty.craftingPersonality': 'Crafting personality',
    'buildWithAgenty.connectingServices': 'Connecting AI services',
    'buildWithAgenty.agentReady': 'Agent ready',
    'buildWithAgenty.yourAgentBorn': 'Your agent is born!',
    'buildWithAgenty.meet': 'Meet',
    'buildWithAgenty.readyToGo': "Your agent is ready to go! Let's see what it can do.",
    'buildWithAgenty.agents': 'Agents',
    'buildWithAgenty.ready': 'Ready',
    'buildWithAgenty.power': 'Power',
    'buildWithAgenty.max': 'Max',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to Agenty',
    'dashboard.monitorAgents': 'Monitor your agents and track performance metrics',
    'dashboard.satisfaction': 'Satisfaction',
    'dashboard.avgResponseTime': 'Avg Response Time',
    'dashboard.conversations': 'Conversations',
    'dashboard.totalAgents': 'Total Agents',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.improvement': 'improvement',
    'dashboard.viewAll': 'View All',
    'dashboard.yourAgents': 'Your Agents',
    'dashboard.manageAndMonitor': 'Manage and monitor your voice AI agents',
    'dashboard.customerSupportBot': 'Customer Support Bot',
    'dashboard.salesAssistant': 'Sales Assistant',
    'dashboard.hebrewSupportBot': 'Hebrew Support Bot',
    'dashboard.conversations_': 'conversations',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.getStartedCommon': 'Get started with common tasks',
    'dashboard.viewAnalytics': 'View Analytics',
    'dashboard.browseTemplates': 'Browse Templates',
    'dashboard.createNewAgent': 'Create New Agent',
    'dashboard.testAgent': 'Test Agent',
    'dashboard.quickTest': 'Quick Test',
    'dashboard.quickTestDesc': 'Quick test with Gemini Live',
    'dashboard.active': 'active',
    'dashboard.inactive': 'inactive',
    'dashboard.paused': 'paused',

    // Pricing
    'pricing.choosePlan': 'Choose Your Plan',
    'pricing.choosePlanDesc': 'Start free or upgrade for full access to all features',
    'pricing.free': 'Free',
    'pricing.perMonth': '/ month',
    'pricing.mostPopular': 'Most Popular',
    'pricing.limitations': 'Limitations',
    'pricing.getStarted': 'Get Started',
    'pricing.upgradeTo': 'Upgrade to',
    'pricing.contactUs': 'Contact Us',
    'pricing.pricingNote': 'All plans include access to knowledge base and ongoing updates',
    'pricing.needCustomPlan': 'Need a custom plan for your business?',

    // Free Plan
    'pricing.freePlan': 'Free Plan',
    'pricing.freePlanDesc': 'Perfect for getting started and exploring the platform',
    'pricing.freeFeature1': 'Create up to 3 agents',
    'pricing.freeFeature2': 'Access to templates',
    'pricing.freeFeature3': 'Test demos with limitations',
    'pricing.freeFeature4': 'Basic analytics',
    'pricing.freeFeature5': 'Community support',
    'pricing.freeLimitation1': 'Limited to 1,000 conversations/month',
    'pricing.freeLimitation2': 'Basic providers only',

    // Standard Plan
    'pricing.standardPlan': 'Standard Plan',
    'pricing.standardPlanDesc': 'For small and medium businesses',
    'pricing.standardFeature1': 'Unlimited agents',
    'pricing.standardFeature2': 'All AI providers (40+)',
    'pricing.standardFeature3': 'Advanced analytics',
    'pricing.standardFeature4': 'Priority support',
    'pricing.standardFeature5': 'API access',
    'pricing.standardFeature6': 'Team collaboration (up to 5 users)',
    'pricing.standardFeature7': 'Custom branding',
    'pricing.standardFeature8': '50,000 conversations/month',

    // Pro Plan
    'pricing.proPlan': 'Pro Plan',
    'pricing.proPlanDesc': 'For large organizations and partners',
    'pricing.proFeature1': 'Everything in Standard',
    'pricing.proFeature2': 'White-label platform',
    'pricing.proFeature3': 'Custom domain support',
    'pricing.proFeature4': 'Dedicated account manager',
    'pricing.proFeature5': 'Agent creation assistance',
    'pricing.proFeature6': 'Unlimited team members',
    'pricing.proFeature7': 'Unlimited conversations',
    'pricing.proFeature8': 'SLA guarantee',
    'pricing.proFeature9': 'Custom integrations',
    'pricing.proFeature10': 'Revenue sharing options',

    // Pipeline Builder
    'builder.pipelineBuilder': 'Pipeline Builder',
    'builder.speechToText': 'Speech to Text',
    'builder.languageModel': 'Language Model',
    'builder.textToSpeech': 'Text to Speech',
    'builder.filter': 'Filter',
    'builder.aggregator': 'Aggregator',
    'builder.customFunction': 'Custom Function',
    'builder.sttDescription': 'Convert speech to text',
    'builder.llmDescription': 'Process and understand text',
    'builder.ttsDescription': 'Convert text to speech',
    'builder.filterDescription': 'Filter and process data',
    'builder.aggregatorDescription': 'Aggregate and combine data',
    'builder.customDescription': 'Custom processing function',
    'builder.valid': 'Valid',
    'builder.invalid': 'Invalid',
    'builder.validate': 'Validate',
    'builder.export': 'Export',
    'builder.reset': 'Reset',
    'builder.save': 'Save',
    'builder.pipelineInfo': 'Pipeline Info',
    'builder.nodes': 'Nodes',
    'builder.connections': 'Connections',
    'builder.status': 'Status',
    'builder.incomplete': 'Incomplete',
    'builder.howToUse': 'How to Use',
    'builder.dragInstructions': 'Drag components from this toolbar to the canvas',
    'builder.connectInstructions': 'Connect components by dragging from output to input handles',
    'builder.configureInstructions': 'Click on components to configure their settings',
    'builder.coreComponents': 'Core Components',
    'builder.processingComponents': 'Processing Components',
    'builder.tips': 'Tips',
    'builder.tip1': 'Start with STT → LLM → TTS for basic voice agent',
    'builder.tip2': 'Add filters and aggregators for advanced processing',
    'builder.tip3': 'Validate your pipeline before saving',
    'builder.nodeConfiguration': 'Node Configuration',
    'builder.basicInformation': 'Basic Information',
    'builder.nodeLabel': 'Node Label',
    'builder.nodeType': 'Node Type',
    'builder.nodeId': 'Node ID',
    'builder.enterNodeLabel': 'Enter node label',
    'builder.providerSelection': 'Provider Selection',
    'builder.providerConfiguration': 'Provider Configuration',
    'builder.configurationStatus': 'Configuration Status',
    'builder.fullyConfigured': 'Fully Configured',
    'builder.requiresConfiguration': 'Requires Configuration',
    'builder.saveConfiguration': 'Save Configuration',
    'builder.confirmDeleteNode': 'Are you sure you want to delete this node?',
    'builder.confirmResetPipeline': 'Are you sure you want to reset the pipeline? All changes will be lost.',
    'builder.noConfigurationAvailable': 'No configuration available for this node type',
    'builder.newPipeline': 'New Pipeline',
    'builder.defaultPipelineDescription': 'A new pipeline for building voice AI agents',

    // Marketplace
    'marketplace.title': 'Agent Marketplace',
    'marketplace.description': 'Discover, share, and install AI agents created by the community',
    'marketplace.publishAgent': 'Publish Agent',
    'marketplace.searchPlaceholder': 'Search agents, categories, or features...',
    'marketplace.allCategories': 'All Categories',
    'marketplace.mostPopular': 'Most Popular',
    'marketplace.newest': 'Newest',
    'marketplace.highestRated': 'Highest Rated',
    'marketplace.mostDownloaded': 'Most Downloaded',
    'marketplace.discover': 'Discover',
    'marketplace.featured': 'Featured',
    'marketplace.trending': 'Trending',
    'marketplace.myAgents': 'My Agents',
    'marketplace.noAgentsFound': 'No agents found',
    'marketplace.tryAdjustCriteria': 'Try adjusting your search criteria or browse different categories',
    'marketplace.clearFilters': 'Clear Filters',
    'marketplace.shareYourAgents': 'Share your agents',
    'marketplace.publishToMarketplace': 'Publish your agents to the marketplace and help the community',
    'marketplace.publishFirstAgent': 'Publish Your First Agent',
    'marketplace.by': 'by',
    'marketplace.premium': 'Premium',
    'marketplace.free': 'Free',
    'marketplace.rating': 'Rating',
    'marketplace.downloads': 'Downloads',
    'marketplace.activeUsers': 'Active Users',
    'marketplace.responseTime': 'Response Time',
    'marketplace.addToAgents': 'Add to Agents',
    'marketplace.adding': 'Adding...',
    'marketplace.addedSuccess': 'Agent added successfully!',
    'marketplace.addedDescription': 'has been added to your agents.',
    'marketplace.addFailed': 'Failed to add agent',
    'marketplace.tryAgainLater': 'Please try again later.',
    'marketplace.backToMarketplace': 'Back to Marketplace',
    'marketplace.about': 'About',
    'marketplace.keyFeatures': 'Key Features',
    'marketplace.performanceMetrics': 'Performance Metrics',
    'marketplace.totalConversations': 'Total Conversations',
    'marketplace.customerSatisfaction': 'Customer Satisfaction',
    'marketplace.category': 'Category',
    'marketplace.aiProviders': 'AI Providers',
    'marketplace.servicesUsed': 'Services used by this agent',
    'marketplace.supportedLanguages': 'Supported Languages',
    'marketplace.configuration': 'Configuration',
    'marketplace.reviews': 'Reviews',
    'marketplace.changelog': 'Changelog',
    'marketplace.overview': 'Overview',
    'marketplace.noReviewsYet': 'No reviews yet',
    'marketplace.firstToReview': 'Be the first to review this agent',
    'marketplace.latestUpdate': 'Latest Update',
    'marketplace.performanceImprovements': 'Performance improvements',
    'marketplace.bugFixes': 'Bug fixes and stability enhancements',
    'marketplace.conversations': 'Conversations',
    'marketplace.response': 'Response',
    'marketplace.users': 'Users',
    'marketplace.addToYourAgents': 'Add to Your Agents',
    'marketplace.customerService': 'Customer Service',
    'marketplace.ecommerce': 'E-commerce',
    'marketplace.healthcare': 'Healthcare',
    'marketplace.education': 'Education',
    'marketplace.finance': 'Finance',
    'marketplace.entertainment': 'Entertainment',
    'marketplace.productivity': 'Productivity',

    // Agents
    'agents.agents': 'Agents',
    'agents.createAgent': 'Create Agent',
    'agents.createNewAgent': 'Create New Agent',
    'agents.editAgent': 'Edit Agent',
    'agents.manageYourAgents': 'Manage your agents',
    'agents.basicInformation': 'Basic Information',
    'agents.basicInformationDesc': 'General information about your agent',
    'agents.aiConfiguration': 'AI Configuration',
    'agents.aiConfigurationDesc': 'Configure the AI services for your agent',
    'agents.agentName': 'Agent Name',
    'agents.enterAgentName': 'Enter agent name',
    'agents.description': 'Description',
    'agents.enterDescription': 'Enter description',
    'agents.status': 'Status',
    'agents.deploymentType': 'Deployment Type',
    'agents.selectStatus': 'Select status',
    'agents.selectDeploymentType': 'Select deployment type',
    'agents.draft': 'Draft',
    'agents.webRTC': 'WebRTC',
    'agents.phoneCall': 'Phone Call',
    'agents.whatsApp': 'WhatsApp',
    'agents.apiOnly': 'API Only',
    'agents.speechToText': 'Speech to Text',
    'agents.languageModel': 'Language Model',
    'agents.textToSpeech': 'Text to Speech',
    'agents.systemPrompt': 'System Prompt',
    'agents.enterSystemPrompt': 'Enter system prompt',
    'agents.systemPromptDesc': 'The instructions your agent will follow',
    'agents.provider': 'Provider',
    'agents.model': 'Model',
    'agents.language': 'Language',
    'agents.voice': 'Voice',
    'agents.temperature': 'Temperature',
    'agents.maxTokens': 'Max Tokens',
    'agents.saving': 'Saving...',
    'agents.saveChanges': 'Save Changes',
    'agents.creating': 'Creating...',
    'agents.configureYourAgent': 'Configure your agent',
    'agents.useTemplate': 'Use Template',
    'agents.editingAgent': 'Editing agent',
    'agents.nameRequired': 'Agent name is required',
    'agents.descriptionRequired': 'Description is required',
    'agents.systemPromptRequired': 'System prompt is required',
    'agents.agentNotFound': 'Agent not found',
    'agents.agentNotFoundDesc': 'The agent you are looking for does not exist',
    'agents.backToAgents': 'Back to Agents',
    'agents.overview': 'Overview',
    'agents.analytics': 'Analytics',
    'agents.configuration': 'Configuration',
    'agents.totalConversations': 'Total Conversations',
    'agents.activeToday': 'Active Today',
    'agents.template': 'Template',
    'agents.created': 'Created',
    'agents.lastUpdated': 'Last Updated',
    'agents.test': 'Test',
    'agents.edit': 'Edit',
    'agents.duplicate': 'Duplicate',
    'agents.deploy': 'Deploy',
    'agents.stop': 'Stop',
    'agents.confirmDelete': 'Are you sure you want to delete this agent?',
    'agents.searchAgents': 'Search agents',
    'agents.filterByStatus': 'Filter by status',
    'agents.allStatuses': 'All statuses',
    'agents.sortBy': 'Sort by',
    'agents.name': 'Name',
    'agents.noAgentsFound': 'No agents found',
    'agents.noAgentsYet': 'You don\'t have any agents yet',
    'agents.tryAdjustingFilters': 'Try adjusting your filters',
    'agents.createFirstAgent': 'Create your first agent',
    'agents.advancedConfiguration': 'Advanced Configuration',
    'agents.advancedConfigurationDesc': 'Customize voice personality, interruption handling, context management, and more',

    // Templates
    'templates.agentTemplates': 'Agent Templates',
    'templates.chooseTemplate': 'Choose a template to get started quickly',
    'templates.popularTemplates': 'Popular Templates',
    'templates.mostUsedTemplates': 'Most used templates by the community',
    'templates.searchTemplates': 'Search templates',
    'templates.filterByCategory': 'Filter by category',
    'templates.allCategories': 'All categories',
    'templates.sortBy': 'Sort by',
    'templates.popular': 'Popular',
    'templates.rating': 'Rating',
    'templates.recent': 'Recent',
    'templates.name': 'Name',
    'templates.all': 'All',
    'templates.noTemplatesFound': 'No templates found',
    'templates.tryAdjustingFilters': 'Try adjusting your filters',
    'templates.clearFilters': 'Clear filters',
    'templates.useTemplate': 'Use Template',
    'templates.customerService': 'Customer Service',
    'templates.sales': 'Sales',
    'templates.hospitality': 'Hospitality',
    'templates.ecommerce': 'E-commerce',
    'templates.healthcare': 'Healthcare',
    'templates.education': 'Education',
    'templates.finance': 'Finance',
    'templates.general': 'General',
    'templates.preview': 'Preview',
    'templates.description': 'Description',
    'templates.configuration': 'Configuration',
    'templates.aiConfiguration': 'AI Configuration',
    'templates.templateInfo': 'Template Info',
    'templates.category': 'Category',
    'templates.deploymentOptions': 'Deployment Options',
    'templates.tags': 'Tags',
    'templates.createdBy': 'Created by',
    'templates.lastUpdated': 'Last updated',
    'templates.actions': 'Actions',
    'templates.previewTemplate': 'Preview Template',
    'templates.customizeTemplate': 'Customize Template',
    'templates.similarTemplates': 'Similar Templates',
    'templates.noSimilarTemplates': 'No similar templates found',
    'templates.templateNotFound': 'Template not found',
    'templates.templateNotFoundDesc': 'The template you are looking for does not exist',
    'templates.backToTemplates': 'Back to Templates',
    'templates.uses': 'uses',

    // Common
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.optional': 'Optional'
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  // Load saved language from localStorage
  useEffect(() => {
    const saved = localStorage.getItem('language') as Language || 'en'

    setLanguageState(saved)
    document.documentElement.dir = saved === 'he' ? 'rtl' : 'ltr'
    document.documentElement.lang = saved

    // Also ensure the body has correct attributes
    if (document.body) {
      document.body.setAttribute('dir', saved === 'he' ? 'rtl' : 'ltr')
      document.body.setAttribute('lang', saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    // Update document direction immediately
    const direction = lang === 'he' ? 'rtl' : 'ltr'
    document.documentElement.dir = direction
    document.documentElement.lang = lang

    // Also update body direction immediately
    if (document.body) {
      document.body.setAttribute('dir', direction)
      document.body.setAttribute('lang', lang)
    }

    // Force a re-render by triggering a minimal layout change
    document.body.style.transform = 'translateX(0px)'
    setTimeout(() => {
      document.body.style.transform = ''
    }, 1)
  }

  const t = (key: string, namespace?: string) => {
    const fullKey = namespace ? `${namespace}.${key}` : key
    return translations[language][fullKey] || key
  }

  const isHebrew = language === 'he'

  const getLanguageClasses = (baseClasses: string = '') => {
    const hebrewClasses = isHebrew ? 'hebrew' : ''
    return [baseClasses, hebrewClasses].filter(Boolean).join(' ')
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isHebrew, getLanguageClasses }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}